import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        {children}
        {/* Iklan Popunder */}
        <Script
          src="https://pl31616162.profitableratecpmnetwork.com/0e/14/b8/0e14b8ee3a3094662dd4f1eee02fa0f9.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
